### ISSUE TITLE
Bad definition of variable SUBDIVX_URL

### ISSUE THREAD

**Issue by Spheres-cu** [csq/subdivx-dl#4]
E:\Media\Series\House of the Dragon S02>subdivx-dl House.of.the.Dragon.S02E02.1080p.10bit.WEBRip.6CH.x265.HEVC-PSA.mkv
Traceback (most recent call last):
  File "C:\Users\Sphere-cu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Sphere-cu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sphere-cu\AppData\Local\Programs\Python\Python310\Scripts\subdivx-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\Sphere-cu\AppData\Local\Programs\Python\Python310\lib\site-packages\subdivx_dl\main.py", line 20, in <module>
    setCookie(https, headers, SUBDIVX_URL)
  File "C:\Users\Sphere-cu\AppData\Local\Programs\Python\Python310\lib\site-packages\subdivx_dl\utils.py", line 606, in setCookie
    cookie = getCookie(https, SUBDIVX_URL)
**NameError: name 'SUBDIVX_URL' is not defined**

subdivx-dloader dev

**Comment by csq** [comment]
Fixed in https://github.com/csq/subdivx-dl/commit/677e5ffea9b8e8d152108989e9a2a99f9a4b3adb. Thanks!
