### ISSUE TITLE
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso

### ISSUE THREAD

**Issue by Spheres-cu** [csq/subdivx-dl#5]
Working...
Traceback (most recent call last):
  File "C:\Users\Spheres-cu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Spheres-cu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Proyectos\subdivx-dl\subdivx_dl\main.py", line 106, in <module>
    main()
  File "D:\Proyectos\subdivx-dl\subdivx_dl\main.py", line 99, in main
    getSubtitle(args, https, url)
  File "D:\Proyectos\subdivx-dl\subdivx_dl\utils.py", line 466, in getSubtitle
    downloadFile(poolManager, url, fpath)
  File "D:\Proyectos\subdivx-dl\subdivx_dl\utils.py", line 57, in downloadFile
    os.rename(tempFile.name, newFilePath)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Users\\Spheres-cu\\AppData\\Local\\Temp\\tmptysl10ym\\tmpykpawc2x' -> 'C:\\Users\\Spheres-cu\\AppData\\Local\\Temp\\tmptysl10ym\\tmpykpawc2x.zip'

Problem download subs in  Windows

Spheres-cu 
subdivx-dloader

inconmig new version
/
[subdivx-dloader](https://github.com/Spheres-cu/subdivx-dloader)

**Comment by csq** [comment]
Fixed in https://github.com/csq/subdivx-dl/commit/5a15d5b02f1192bc75b74d831bced3b1675b2efb.
